# Generated by Django 5.0.4 on 2024-05-07 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_userprofile_adress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
