# Generated by Django 5.0.4 on 2024-05-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
